dataset: CIFAR10
arch: activethief_cnn
seed: 0
victim_id: cifar10_activethief_cnn
out: runs/victims/cifar10_activethief_cnn_seed0.pt
save_metadata: true
train:
  epochs: 300
  batch_size: 150
  scheduler: multistep
  dropout_prob: 0.2
  num_workers: 0
  optimizer:
    name: adam
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.001
