attack:
  name: dfme
  output_mode: soft_prob
  max_budget: 20000000
  batch_size: 256
  n_g_steps: 1
  n_s_steps: 5
  grad_approx_m: 1
  grad_approx_epsilon: 0.001
  generator_lr: 0.0001
  noise_dim: 256
  internal_input_scale_mode: tanh

substitute:
  arch: resnet18
  width_mult: 1
  init_seed: 1234
  optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005

budget:
  max_budget: 20000000
  checkpoints: [100000, 1000000, 5000000, 10000000, 15000000, 20000000]
