attack:
  name: ds
  output_mode: soft_prob
  max_budget: 20000000
  eval_interval_queries: 1000000
  batch_size: 256
  noise_dim: 256
  g_iter: 1
  d_iter: 5
  num_students: 2
  loss: l1
  generator_loss: l1
  student_lr: 0.3
  generator_lr: 0.0001
  strict_iteration_budget: true
  lr_decay_milestones_ratio:
  - 0.1
  - 0.3
  - 0.5
  lr_decay_gamma: 0.3
substitute:
  arch: resnet18
  width_mult: 1
  init_seed: 1234
  optimizer:
    name: sgd
    lr: 0.3
    momentum: 0.9
    weight_decay: 0.0005
budget:
  max_budget: 20000000
  checkpoints:
  - 100000
  - 1000000
  - 5000000
  - 10000000
  - 15000000
  - 20000000
